---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: 0.0.0.0
server.port: 5601
elasticsearch.url: http://0.0.0.0:9200


#logging.dest: /var/log/kibana/kibana.log
#xpack.monitoring.ui.container.elasticsearch.enabled: false
